spring.application.name=first-spring

server.port=8081

# Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true  # Enables H2 web console
spring.h2.console.path=/h2-console  # Access DB at http://localhost:8081/h2-console

# Liquibase settings (use YAML instead of XML)
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
